Titanbot.Web/Models/Command.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Titanbot.Web.Models.Enums;

namespace Titanbot.Web.Models
{
    public class Command
    {
        public string Name { get; set; }
        public string Description { get; set; }
        public List<string> Aliases { get; set; } = new List<string>();
        public CommandGroup Group { get; set; }
        public DefaultPerms DefaultPerm { get; set; }
        public List<string> Usages { get; set; } = new List<string>();
        public List<CommandFlag> Flags { get; set; } = new List<CommandFlag>();
        public string Notes { get; set; }
    }
}

Titanbot.Web/Models/CommandFlag.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Titanbot.Web.Models
{
    public class CommandFlag
    {
        public char ShortInvokation { get; set; }
        public string Invokation { get; set; }
        public string Description { get; set; }
        public List<string> Arguments { get; set; } = new List<string>();

        public string ShortInvokationString() => "-" + ShortInvokation;
        public string InvokationString() => "--" + Invokation;

        public string GetArguments()
        {
            if (Arguments.Count <= 0)
                return "";

            // Combine arguments
            var aggregated = Arguments.Aggregate("", (current, arg) => current + "<" + arg + "> ");

            // Trim last space
            return aggregated.Remove(aggregated.Length - 1);
        }
    }
}

Titanbot.Web/Models/CommandModels/Command.cs
using System.Collections.Generic;
using Titanbot.Web.Models.CommandModels.Enums;

namespace Titanbot.Web.Models.CommandModels
{
    public class Command
    {
        public string Name { get; set; }
        public string Description { get; set; }
        public List<string> Aliases { get; set; } = new List<string>();
        public CommandGroup Group { get; set; }
        public DefaultPerms DefaultPerm { get; set; }
        public List<string> Usages { get; set; } = new List<string>();
        public List<CommandFlag> Flags { get; set; } = new List<CommandFlag>();
        public string Notes { get; set; }
    }
}

Titanbot.Web/Models/CommandModels/CommandFlag.cs
using System.Collections.Generic;
using System.Linq;

namespace Titanbot.Web.Models.CommandModels
{
    public class CommandFlag
    {
        public char ShortInvokation { get; set; }
        public string Invokation { get; set; }
        public string Description { get; set; }
        public List<string> Arguments { get; set; } = new List<string>();

        public string ShortInvokationString() => "-" + ShortInvokation;
        public string InvokationString() => "--" + Invokation;

        public string GetArguments()
        {
            if (Arguments.Count <= 0)
                return "";

            // Combine arguments
            var aggregated = Arguments.Aggregate("", (current, arg) => current + "<" + arg + "> ");

            // Trim last space
            return aggregated.Remove(aggregated.Length - 1);
        }
    }
}

Titanbot.Web/Models/CommandModels/Enums/CommandGroup.cs
namespace Titanbot.Web.Models.CommandModels.Enums
{
    public enum CommandGroup
    {
        General,
        Admin,
        Owner,
        Data,
        Clan,
        Bot
    }
}

Titanbot.Web/Models/CommandModels/Enums/DefaultPerms.cs
namespace Titanbot.Web.Models.CommandModels.Enums
{
    public enum DefaultPerms
    {
        Everyone,
        Administrator,
        Owner
    }
}

Titanbot.Web/ViewModels/AllCommands.cs
using System.Collections.Generic;
using System.Linq;
using Titanbot.Web.Models;
using Titanbot.Web.Models.CommandModels;
using Titanbot.Web.Models.CommandModels.Enums;

namespace Titanbot.Web.ViewModels
{
    public class AllCommands
    {
        public List<Command> Commands { get; set; }

        public List<CommandGroup> PriorityGroups => new List<CommandGroup>
        {
            CommandGroup.General,
            CommandGroup.Admin,
            CommandGroup.Clan,
            CommandGroup.Data,
            CommandGroup.Bot
        };
    }
}

Titanbot.Web/Controllers/AboutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace Titanbot.Web.Controllers
{
    public class AboutController : Controller
    {
        // GET: /<controller>/
        public IActionResult Index()
        {
            return View();
        }
    }
}

Titanbot.Web/Controllers/AccountController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Titanbot.Web.LoginManagers;

namespace Titanbot.Web.Controllers
{
    public class AccountController : Controller
    {
        private readonly CookieSignInManager _signInManager;
        
        

        public AccountController(CookieSignInManager signInManager)
        {
            _signInManager = signInManager;
        }

        [TempData]
        public string ErrorMessage { get; set; }
        
        public IActionResult Login()
        {
            var redirectUrl = Url.Action(nameof(LoginCallback), "Account");
            var properties = _signInManager.ConfigureExternalAuthenticationProperties(redirectUrl);
            return Challenge(properties, CookieSignInManager.Provider);
        }

        public async Task<IActionResult> LoginCallback(string remoteError = null)
        {
            if (remoteError != null)
            {
                ErrorMessage = $"Error from Discord: {remoteError}";
                return RedirectToAction(nameof(HomeController.Index), "Home");
            }

            var info = await _signInManager.GetExternalLoginInfoAsync();
            if (info == null)
                return RedirectToAction(nameof(HomeController.Index), "Home");

            await _signInManager.SignInAsync(info.Principal);


            return RedirectToAction(nameof(HomeController.Index), "Home");
        }

        public async Task<IActionResult> Logout()
        {
            await _signInManager.SignOutAsync();
            return RedirectToAction(nameof(HomeController.Index), "Home");
        }
    }
}

Titanbot.Web/Controllers/ExampleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Titanbot.Web.ViewModels;
using Titanbot.Web._HardcodedValues;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace Titanbot.Web.Controllers
{
    public class ExampleController : Controller
    {
        private readonly HardcodedCommands _hardcodedCommands;

        public ExampleController(HardcodedCommands hardcodedCommands)
        {
            _hardcodedCommands = hardcodedCommands;
        }

        // GET: /<controller>/
        public IActionResult Index()
        {
            var model = new AllCommands
            {
                Commands = _hardcodedCommands.Commands
            };

            return View(model);
        }
    }
}

Titanbot.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace Titanbot.Web.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Error()
        {
            return View();
        }
    }
}

Titanbot.Web/Controllers/SettingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace Titanbot.Web.Controllers
{
    public class SettingController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Titanbot.Web/Views/About/Index.cshtml
@{
    ViewData["Title"] = "About";
}

<div class="card m-2">
    <div class="card-body">
        <h4 class="card-title">An overview of Titanbot</h4>
        <p class="card-text">
            Titanbot is currently an open sourced Discord Bot programmed in .NET and is used by people or clans who play
            <a href="http://www.gamehive.com/games/tap-titans-2" target="_blank">Tap Titans 2</a>
            and can provide useful information about the game. It can also be managed by clans to
            set a timer until their next Clan Quest is up, and much, much more.
        </p>
    </div>
</div>
<div class="card m-2">
    <div class="card-header">
        The projects
    </div>
    <div class="card-body">
        <h4 class="card-title">The open source Titanbot</h4>
        <p class="card-text">
            Titanbot is a bit special, in the case that there is a base component, and a Tap Titans 2 component.
            The base component can be developed to suit the needs of the indidual game and is basically a lightweight implementation
            of a Discord Bot, which contains the base functionality.
            The Tap Titans 2 component is tailored towards showing information about the game. Doing some math for you and most importantly,
            manage the Clan Quests timer.
            <hr />
            Links to the projects: <br />
            <a href="https://github.com/Titansmasher/TitanBot" target="_blank" class="btn btn-primary">The base</a>
            <a href="https://github.com/Titansmasher/TT2Bot" target="_blank" class="btn btn-primary">The extension</a>
            <a href="https://github.com/MildanWorld/Titanbot-Website" target="_blank" class="btn btn-primary">The website</a>

        </p>
    </div>
</div>
    
<div class="card m-2">
    <div class="card-header">
        Support the project
    </div>
    <div class="card-body">
        <h4 class="card-title">Hosting costs</h4>
        <p class="card-text">
            There is a hosting cost to the Discord bot, where Titansmasher is renting out a server for it to be run 24/7 on.
            If you want to support this hosting cost for it to continue running, you can donate to him
            <a href="https://www.patreon.com/titansmasher" target="_blank">here</a>.
        </p>
        <p class="card-text">
            Currently the hosting of the website is free via <a href="https://www.heroku.com/" target="_blank">Heroku</a>,
            but this may be subject to change since this is the first time Mildan is trying it.
        </p>
    </div>
</div>
    
<div class="card m-2">
    <div class="card-header">
        The team
    </div>
    <div class="card-body">
        <h4 class="card-title">Titansmasher and Mildan</h4>
        <p class="card-text">
            A brit and a dane, up to no good.
        </p>
    </div>
</div>

Titanbot.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home";
}

<div>
    <h1>Welcome to the Titanbot website!</h1>
    <p>
        Do keep in mind that this website is still in very early development, but we decided to release it early
        just for the sake of showing off some examples on how you can invite the bot to your server, configure it,
        and use some of the commands. This can be found in the <a asp-controller="Example" asp-action="Index">Examples</a> page. <br/>
        This page will contain most of the information for now. Additional information about Titanbot, the project,
        the hosting of the bot and website, and the team behind it, can be found in the 
        <a asp-controller="About" asp-action="Index">About</a> page. <br/>
        The website will be updated in the coming weeks, with more content. Until then, the website will function as an
        information hub on how to use the Titanbot via discord. Thank your for your interest, and if you have anything to say at all,
        feel free to come by our Discord guild <a href="http://discord.gg/abQPtHu" target="_blank">Yort Kingdom</a> and have a chat. <br/>
        <span style="font-size: 50%">All complaints must go to Titansmasher though.</span>
    </p>
</div>

Titanbot.Web/Views/Setting/Index.cshtml
@{
    ViewData["Title"] = "Settings";
}

<div>
    <h1>Some info on the settings of Titanbot will be here.</h1>
</div>

Titanbot.Web/Views/Shared/_Layout.cshtml
@*@inject Microsoft.ApplicationInsights.AspNetCore.JavaScriptSnippet JavaScriptSnippet*@
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>@ViewData["Title"] - Titanbot</title>

    <environment names="Development">
        <link rel="shortcut icon" type="image/x-icon" href="~/images/favicon.ico" />
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css"/>
        <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    </environment>
    <environment names="Staging,Production">
        <link rel="shortcut icon" type="image/x-icon" href="~/images/favicon.ico" />
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M"
              crossorigin="anonymous"/>
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true"/>
    </environment>
    @*@Html.Raw(JavaScriptSnippet.FullScript)*@
</head>
<body>
    <nav class="navbar navbar-expand-sm fixed-top navbar-dark bg-dark">
        <div class="container">
            <a class="navbar-brand" asp-controller="Home" asp-action="Index">
                <img src="~/images/logo.png" width="50" height="50" alt="" 
                     class="rounded-circle" />
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav mr-auto">
                    <li>
                        <a class="nav-link" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li>
                        <a class="nav-link" asp-controller="Example" asp-action="Index">Examples</a>
                    </li>
                    <li>
                        <a class="nav-link" href="https://discordapp.com/oauth2/authorize?client_id=271318229610266625&scope=bot&permissions=8" target="_blank">Invite</a>
                    </li>
                    <li>
                        <a class="nav-link" asp-controller="Setting" asp-action="Index">Settings</a>
                    </li>
                </ul>
                <ul class="navbar-nav ml-auto">
                    <li>
                        <a class="nav-link" asp-controller="About" asp-action="Index">About</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <div class="container body-content">
        <div class="alert alert-warning" role="alert">
            Teabot will be shutting down on the 30th of September, 2018, due to the makers not actively playing Tap Titans any longer and we have lost our
            interest in maintaining the bot and continuing development. But fret not! There is a new bot in development for you made by effrill3#0001. <br />
            Invite the new bot by <a href="https://discordapp.com/api/oauth2/authorize?client_id=466854404965007360&permissions=2146954487&scope=bot" target="_blank">clicking this link</a> or you can join the support sere with the following join code: <a href="https://discord.gg/WvcryZW" target="_blank">WvcryZW</a> <br /> <br />
            It's been an honor and it's been very fun to try and make something like this for the community, and we hope you enjoyed the ride.
        </div>
        @RenderBody()
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/js/popper/popper.min.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" 
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js" 
                asp-fallback-test="window.jQuery"
                integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous">
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" 
                asp-fallback-src="~/js/popper/popper.min.js"
                integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous">
        </script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" 
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous">
        </script>

        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>